name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Build Docker images
      run: |
        docker build -t webhook:latest ./src/Webhook.Navferty/

    - name: Tag Docker image with commit SHA
      id: docker_tag
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
    
    - name: Push Docker images to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag webhook:latest $DOCKER_USERNAME/webhook:latest
        docker tag webhook:latest $DOCKER_USERNAME/webhook:${{ steps.docker_tag.outputs.sha }}
        docker push $DOCKER_USERNAME/webhook:latest
        docker push $DOCKER_USERNAME/webhook:${{ steps.docker_tag.outputs.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key docker-compose.yml $SERVER_USER@$SERVER_HOST:~/webhook/docker-compose.yml
        ssh -i private_key $SERVER_USER@$SERVER_HOST << 'EOF'
          set -e
          cd ./webhook
          docker compose pull
          docker compose down
          docker compose up -d
        EOF
